
The following have been reloaded with a version change:
  1) pillow/7.2.0-python-3.7.4 => pillow/6.2.1


The following have been reloaded with a version change:
  1) pillow/6.2.1 => pillow/7.2.0-python-3.7.4


The following have been reloaded with a version change:
  1) icu/65.1 => icu/64.2

Using CUDA device0 _CudaDeviceProperties(name='Tesla P100-PCIE-12GB', total_memory=12198MB)
           device1 _CudaDeviceProperties(name='Tesla P100-PCIE-12GB', total_memory=12198MB)
           device2 _CudaDeviceProperties(name='Tesla P100-PCIE-12GB', total_memory=12198MB)
           device3 _CudaDeviceProperties(name='Tesla P100-PCIE-12GB', total_memory=12198MB)

Traceback (most recent call last):
  File "train.py", line 440, in <module>
    dist.init_process_group(backend='nccl', init_method='env://')  # distributed backend
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch-geometric/1.6.1-python-3.7.4-pytorch-1.6.0/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch-geometric/1.6.1-python-3.7.4-pytorch-1.6.0/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch-geometric/1.6.1-python-3.7.4-pytorch-1.6.0/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch-geometric/1.6.1-python-3.7.4-pytorch-1.6.0/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/bin/python3', '-u', 'train.py', '--local_rank=3', '--batch-size', '64', '--data', 'custom_train/dataset_fs.yaml', '--weights', 'weights/yolov5l.pt']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

real	0m4.374s
user	0m2.510s
sys	0m0.998s
